### ISSUE TITLE
SimpleTreeNode.addChildNode is not public

### ISSUE THREAD

**Issue by wickeduk** [davidsusu/tree-printer#1]
And so it's not possible to add any nodes.

**Comment by davidsusu** [comment]
Thank you for the report. It's now `public`.

**Comment by wickeduk** [comment]
Thanks, can this be uploaded to mvnrepository.

**Comment by davidsusu** [comment]
It was already published, as `1.1`:

https://search.maven.org/artifact/hu.webarticum/tree-printer/1.1/jar
