### ISSUE TITLE
documentation & export to DOT

### ISSUE THREAD

**Issue by amryounis** [davidsusu/tree-printer#12]
hi, where I could find the API doc? do you support exporting to dot format?

**Comment by davidsusu** [comment]
Currently, I don't host an API docs site. You can [download it as a jar artifact from the Maven Central](https://repo1.maven.org/maven2/hu/webarticum/tree-printer/3.1.0/tree-printer-3.1.0-javadoc.jar), or generate it locally using the `javadoc` gradle task.

There is no support for integration with Graphviz (or any other data structure library). If you are a Graphviz expert, I welcome any pull request related to this. Also, you can write your own tree implementation that prints DOT output.

**Comment by amryounis** [comment]
thank you
