### ISSUE TITLE
How best to carry contextual information via the Tree into a Listing?

### ISSUE THREAD

**Issue by andrewliles** [davidsusu/tree-printer#9]
Thank you, David, for this library.

I have used it to produce a tree listed of people's names, here is an example, (illustrated with made-up names) as rows in a spreadsheet.  I use the `ListingTreePrinter` to (a) sequence the relationships (b) create an "ASCII" tree presentation.  

![image](https://user-images.githubusercontent.com/4592654/204140201-59109ca9-5b91-48a0-950c-ef0a81506bbe.png)

I have been using v2.x.  In order to achieve this, I had to overload the `TreeNode.content()` method to contain not just the people's names, but also an identifier appended on the end (name was concatenated with `@` then the identifier.  Then parse the `ListingTreePrinter.print()` output splitting using the following Regex 

`(.*)@(.{26}\n`

to obtains the line elements and the Identifier.

How could I achieve this in a more elegant way; as there are no protected/public methods, I cannot subclass the ListingTreePrinter?  Or would you be happy to receive a PR for an alternate public method, maybe something like:

```
  List<ListNode> ListingTreePrinter.getListNodes(TreeNode rootNode)
```

where `ListNode` contains the listing prefix e.g. " │   ├─ " and the original `TreeNode`.

**Comment by davidsusu** [comment]
Thank you for your idea, it's interesting. To be honest, I haven't thought much about using this lib outside of the console.

I will check your pull-request soon, but I will most likely have some change requests.

Special thanks for the unit tests.
